//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emre_tatliyer_h5190021_yonlendirilmiscalismaproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMusteriAdres
    {
        public int MusteriAdresId { get; set; }
        public int MusteriId { get; set; }
        public string MusteriAdres { get; set; }
        public string MusteriAdresIl { get; set; }
        public string MusteriAdresIlce { get; set; }
        public string MusteriAdresAdi { get; set; }
        public string MusteriAdresDurum { get; set; }
    
        public virtual TblMusteri TblMusteri { get; set; }
    }
}
