//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emre_tatliyer_h5190021_yonlendirilmiscalismaproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMusteriKart
    {
        public int MusteriKartId { get; set; }
        public int MusteriId { get; set; }
        public string MusteriKartAdi { get; set; }
        public string MusteriKartNo { get; set; }
        public string MusteriKartUstuIsim { get; set; }
        public string MusteriKartTarih { get; set; }
        public string MusteriKartCV { get; set; }
        public string MusteriKartDurum { get; set; }
    
        public virtual TblMusteri TblMusteri { get; set; }
    }
}
