//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emre_tatliyer_h5190021_yonlendirilmiscalismaproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMagazaTuru
    {
        public int MagazaTuruId { get; set; }
        public string MagazaTuru { get; set; }
    }
}
