//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emre_tatliyer_h5190021_yonlendirilmiscalismaproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMagaza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMagaza()
        {
            this.TblUrunler = new HashSet<TblUrunler>();
        }
    
        public int MagazaId { get; set; }
        public int MusteriId { get; set; }
        public Nullable<int> MagazaTuruId { get; set; }
        public string MagazaAdi { get; set; }
        public string MagazaTel { get; set; }
        public string MagazaAdres { get; set; }
        public string MagazaResmi { get; set; }
        public string MagazaMinTutar { get; set; }
        public string MagazaPuan { get; set; }
        public string MagazaSure { get; set; }
    
        public virtual TblMusteri TblMusteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunler> TblUrunler { get; set; }
    }
}
