//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emre_tatliyer_h5190021_yonlendirilmiscalismaproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrun
    {
        public int UrunId { get; set; }
        public string Urunad { get; set; }
        public Nullable<int> UrunFiyati { get; set; }
        public string UrunBilgisi { get; set; }
        public string UrunResmi { get; set; }
    }
}
