//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emre_tatliyer_h5190021_yonlendirilmiscalismaproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrunler
    {
        public int UrunId { get; set; }
        public Nullable<int> MagazaId { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunKategorisi { get; set; }
        public string UrunTuru { get; set; }
        public string UrunFiyat { get; set; }
        public string UrunStock { get; set; }
        public string UrunResim { get; set; }
        public string UrunAciklama { get; set; }
    
        public virtual TblMagaza TblMagaza { get; set; }
    }
}
